### PR TITLE
Big changes

### PR DESCRIPTION
**Pull request by johnnynunez**
Updated Clover v5108
Updated build repository OpenCore v0.5.7

Builds repository kexts:
    AppleALC v1.4.8
    CPUFriend v1.2.0
    HibernationFixup v1.3.2
    Lilu v1.4.3
    NVMeFix v1.0.2
    VirtualSMC (All Tools) v1.1.2
    VoodooI2C v2.3
    VoodooInput v1.0.4
    VoodooPS2Controller (Acidanthera) v2.1.3
    WhateverGreen v1.3.8
    IntelBluetoothFirmware v1.0.3
    USBInjectAll v0.7.5

Changes on Clover and OpenCore

### CODE REVIEW

**Comment by MarshalX** [comment]
IMG_20200331_145129

**Comment by johnnync13** [comment]
@MarshalX the vault is optional... is to sign in opencore.efi. I don't have problems :'(

**Comment by MarshalX** [comment]
@johnnync13 All I did was replace the efi folder with a new one and tried to start.

**Comment by MarshalX** [comment]
Maybe need to update boot (version of OC)?

But as I remember, I use 0.5.7. How I can check current version?

**Comment by MarshalX** [comment]
By the way, macos 10.15.**3**

**Comment by MarshalX** [comment]
Did the same thing as yesterday, only on a USB flash drive. Could start. Parsing errors did not disappear, the message about the vault disappeared. When loading, unlike the previous commit, everything is very gigantic (size of text) in the OpenCore

**Comment by johnnynunez** [comment]
@MarshalX change UIScale on open core

**Comment by boardman21** [comment]
i have got this errors

**Pull request merged**
